server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: 349349
  dbname: CourseFlow
migrations:
  path: "file:backend/migrations"
  db: "postgres"

#file:
#  excel_path: /path/to/excel/files