version: '3'
services:
  auth-service:
    build: ./cmd/auth-service
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=auth-db
      - SMTP_HOST=smtp.example.com
    depends_on:
      - auth-db
      - rabbitmq

  course-service:
    build: ./cmd/course-service
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=course-db
      - REDIS_HOST=redis
    depends_on:
      - course-db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"

  course-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: courseuser
      POSTGRES_PASSWORD: coursepass
      POSTGRES_DB: coursedb
    ports:
      - "5433:5432"